### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Abe-Ha** [MartyMcKnife/BeatSaberSpotify#12]
Sorry if this is a dumb issue:

`[24-Dec-20 22:46:43] [INFO] - run / <module> 33548 - : 

[24-Dec-20 22:46:43] [INFO] - run / <module> 33548 - : Program started
[24-Dec-20 22:46:43] [DEBUG] - beatsaberspotify / __init__ 33548 - : b'Download Directory: C:\\Users\\evils\\Desktop\\BEAT SABER APPS\\Beat.Saber.Spotify.V2.1\\V2.1\\downloads'
[24-Dec-20 22:46:43] [DEBUG] - beatsaberspotify / __init__ 33548 - : b'Custom Songs Directory: X:\\SteamLibrary\\steamapps\\common\\Beat Saber\\Songs'
[24-Dec-20 22:46:43] [DEBUG] - beatsaberspotify / __init__ 33548 - : b'Custom Playlists Directory: X:\\SteamLibrary\\steamapps\\common\\Beat Saber\\Playlist'
[24-Dec-20 22:46:43] [DEBUG] - beatsaberspotify / __init__ 33548 - : Unzip?: False
[24-Dec-20 22:46:43] [INFO] - beatsaberspotify / SpotifyWriter 33548 - : Speaking to Spotify API
[24-Dec-20 22:46:44] [INFO] - beatsaberspotify / SpotifyWriter 33548 - : b'Playlist Name: r e a l l y    h a r d'
[24-Dec-20 22:46:45] [INFO] - util / info 38016 - : after forker raised exception '_thread.lock' object has no attribute '_at_fork_reinit'
[24-Dec-20 22:46:45] [INFO] - util / info 38016 - : child process calling self.run()
[24-Dec-20 22:46:45] [INFO] - util / info 38016 - : manager serving at '\\\\.\\pipe\\pyc-38016-0-eg3rb2oe'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : requesting creation of a shared 'Value' object
[24-Dec-20 22:46:45] [DEBUG] - util / debug 38016 - : 'Value' callable returned object with id '1f15f8482e0'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : INCREF '1f15f8482e0'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : requesting creation of a shared 'dict' object
[24-Dec-20 22:46:45] [DEBUG] - util / debug 38016 - : 'dict' callable returned object with id '1f15f840540'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : INCREF '1f15f840540'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : requesting creation of a shared 'Lock' object
[24-Dec-20 22:46:45] [DEBUG] - util / debug 38016 - : 'Lock' callable returned object with id '1f15f848480'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : INCREF '1f15f848480'
[24-Dec-20 22:46:45] [ERROR] - run / <module> 33548 - : Exception has occured
Traceback (most recent call last):
  File "C:\Users\evils\Desktop\BEAT SABER APPS\Beat.Saber.Spotify.V2.1\V2.1\python\run.py", line 49, in <module>
    bss.run(username, uri)
  File "C:\Users\evils\Desktop\BEAT SABER APPS\Beat.Saber.Spotify.V2.1\V2.1\python\beatsaberspotify.py", line 173, in run
    tracks = [line.rstrip() for line in t]
  File "C:\Users\evils\Desktop\BEAT SABER APPS\Beat.Saber.Spotify.V2.1\V2.1\python\beatsaberspotify.py", line 173, in <listcomp>
    tracks = [line.rstrip() for line in t]
  File "C:\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : DECREF '1f15f8482e0'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 38016 - : disposing of obj with id '1f15f8482e0'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : DECREF '1f15f840540'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 38016 - : disposing of obj with id '1f15f840540'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : DECREF '1f15f848480'
[24-Dec-20 22:46:45] [DEBUG] - util / debug 38016 - : disposing of obj with id '1f15f848480'
[24-Dec-20 22:46:45] [INFO] - util / info 33548 - : sending shutdown message to manager
[24-Dec-20 22:46:45] [DEBUG] - util / debug 38016 - : manager received shutdown message
[24-Dec-20 22:46:45] [INFO] - util / info 38016 - : process shutting down
[24-Dec-20 22:46:45] [DEBUG] - util / debug 38016 - : running all "atexit" finalizers with priority >= 0
[24-Dec-20 22:46:45] [DEBUG] - util / debug 38016 - : running the remaining "atexit" finalizers
[24-Dec-20 22:46:45] [INFO] - util / info 38016 - : process exiting with exitcode 0
[24-Dec-20 22:46:45] [INFO] - util / info 33548 - : process shutting down
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : running all "atexit" finalizers with priority >= 0
[24-Dec-20 22:46:45] [DEBUG] - util / debug 33548 - : running the remaining "atexit" finalizers`

**Comment by MartyMcKnife** [comment]
Looks like another encoding error. Could you please provide me with the link to the playlist so I can investigate?

**Comment by MartyMcKnife** [comment]
Worked it out. Forgot to update an encoding in one of the files. Should be fixed with the latest update
