### ISSUE TITLE
Receiving an error when trying to run.

### ISSUE THREAD

**Issue by badgersdontvote** [MartyMcKnife/BeatSaberSpotify#29]
Hiya,

I have received the following error when I attempt to run the program.

Traceback (most recent call last):
  File "C:\Users\callu\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\callu\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\callu\Downloads\beatspot\python\beatsaberspotify.py", line 120, in downloadSong
    bsSongId, bsSongName, bsUsername = downloader.get_song_info(
  File "C:\Users\callu\Downloads\beatspot\python\beatsaver.py", line 49, in get_song_info
    info = resp.json()
  File "C:\Users\callu\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\callu\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\callu\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\callu\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\callu\Downloads\beatspot\python\run.py", line 50, in <module>
    bss.run(username, uri)
  File "C:\Users\callu\Downloads\beatspot\python\beatsaberspotify.py", line 226, in run
    p.starmap(self.downloadSong, items)
  File "C:\Users\callu\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\callu\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[05-Aug-21 13:40:56] [INFO] - util / info 10988 - : process shutting down
[05-Aug-21 13:40:56] [INFO] - util / info 10988 - : sending shutdown message to manager
[05-Aug-21 13:40:56] [INFO] - util / info 16248 - : process shutting down
[05-Aug-21 13:40:56] [INFO] - util / info 16248 - : process exiting with exitcode 0

Many thanks!!

**Comment by MartyMcKnife** [comment]
Looks like a problem with BeatSaber not sending back any data. Do you know what song this failed with? Best thing I can suggest is to just try running it again

**Comment by badgersdontvote** [comment]
It failed on all different playlists that I tried, youtube as well

**Comment by badgersdontvote** [comment]
[06-Aug-21 10:06:46] [INFO] - util / info 11380 - : process shutting down
[06-Aug-21 10:06:46] [INFO] - util / info 22196 - : process shutting down
[06-Aug-21 10:06:46] [INFO] - util / info 11380 - : process exiting with exitcode 0
[06-Aug-21 10:06:46] [INFO] - util / info 15636 - : process shutting down
[06-Aug-21 10:06:46] [INFO] - util / info 4824 - : process shutting down
[06-Aug-21 10:06:46] [INFO] - util / info 22196 - : process exiting with exitcode 0
[06-Aug-21 10:06:46] [INFO] - util / info 20244 - : process shutting down
[06-Aug-21 10:06:46] [INFO] - util / info 15636 - : process exiting with ex[06-Aug-21 10:06:46] [INFO] - util / info 19516 - : process shutting down
tcode 0
[06-Aug-21 10:06:46] [INFO] - util / info 20244 - : process exiting with exitcode 0
[06-Aug-21 10:06:46] [INFO] - util / info 14024 - : process exiting with exitcode 0
[06-Aug-21 10:06:46] [INFO] - util / info 9008 - : process exiting with exitcode 0

[06-Aug-21 10:06:46] [INFO] - util / info 18960 - : process shutting down
[06-Aug-21 10:06:46] [INFO] - util / info 11624 - : Failure to send message: ('#TRACEBACK', 'Traceback (most recent call last):\n  File "C:\\Users\\callu\\AppData\\Local\\Programs\\Python\\Python38\\lib\\multiprocessing\\connection.py", line 312, in _recv_bytes\n    nread, err = ov.GetOverlappedResult(True)\nBrokenPipeError: [WinError 109] The pipe has been ended\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\Users\\callu\\AppData\\Local\\Programs\\Python\\Python38\\lib\\multiprocessing\\managers.py", line 200, in handle_request\n    connection.deliver_challenge(c, self.authkey)\n  File "C:\\Users\\callu\\AppData\\Local\\Programs\\Python\\Python38\\lib\\multiprocessing\\connection.py", line 739, in deliver_challenge\n    response = connection.recv_bytes(256)        # reject large message\n  File "C:\\Users\\callu\\AppData\\Local\\Programs\\Python\\Python38\\lib\\multiprocessing\\connection.py", line 216, in recv_bytes\n    buf = self._recv_bytes(maxlength)\n  File "C:\\Users\\callu\\AppData\\Local\\Programs\\Python\\Python38\\lib\\multiprocessing\\connection.py", line 321, in _recv_bytes\n    raise EOFError\nEOFError\n')
[06-Aug-21 10:06:46] [INFO] - util / info 11624 - :  ... request was None
[06-Aug-21 10:06:46] [INFO] - util / info 11624 - :  ... exception was BrokenPipeError(32, 'The pipe is being closed', None, 232, None)
[06-Aug-21 10:06:46] [ERROR] - run / <module> 7564 - : Exception has occured
multiprocessing.pool.RemoteTraceback: 

Perhaps this part of the log will also help. I've also attached the whole log alongside this.
[beatsaberspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/6944493/beatsaberspotify.log)

**Comment by MartyMcKnife** [comment]
Ah hah! Shoulda checked BeatSaver first

The entire website has been handed over to new owners, which basically means all of the endpoints are currently broken. 

I'm just about to release a new version of BeatSaberSpotify (hopefully next week), which has been completely rewritten to work as a website. Unfortunately, that means I'm probably not going to fix this issue.

If you can't wait a week, and fancy a bit of programming, open up the beatsaver.py file in /python, and replace all mentions of the _url_ variable with a the new endpoint/url.

The documentation can be found [here](https://api.beatsaver.com/docs/index.htm)

Good Luck!

**Comment by Sephiths** [comment]
So should I wait a couple weeks for the new update/website? I can't seem to get it to work. The only text output I get is it uninstalling and installing the same programs. 

I'd also like to note that Spotify changed the way users get the URI of a playlist. They now have to hold alt when hovering over share to see the option appear to copy.

**Comment by MartyMcKnife** [comment]
Ok so it was close enough to a week. 

You can view the new converter at [https://www.bsmatcher.com](https://www.bsmatcher.com)
